### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jackttcoms** [bfitech/zapchupload#1]
Hi, would you be able to do a simple example of the code in use? Thanks

**Comment by rsur** [comment]
Sample code is available at [`./tests/htdocs-test/index.php`](https://github.com/bfitech/zapchupload/blob/11d5d87de7bbb0f5b053e243690fd465eb91926c/tests/htdocs-test/index.php). Instruction to run it with PHP builtin server is available on the README. See [this vid](https://streamable.com/9zj72) for quick demonstration.

This lib only provides the backend. The frontend itself is language-agnostic. You can make your own frontend implementation as long as it complies with [zapchupload API](https://docs.bfi.io/x1/bfin--zapchupload/1.3.2/html/de/de6/classBFITech_1_1ZapChupload_1_1ChunkUpload.html#ad9c9a799143f63be7aec1d11f9715bcc). However, there's one reference impementation available [here](https://github.com/bfitech/angular-chupload), which the demo above uses.
